name: "Commit and Push to Protected Branch"
description: "A Github Action that is able to push the pending changes of a codebase on a branch protected by pull request."
author: "mail@fabriziocacicia.com"

runs:
  using: "can be composite/docker/..."
  ...
